services:
  personal_website:
    build: .
    container_name: personal_website
    restart: unless-stopped
    networks:
      - caddy_net
    environment:
      - PULSE_SERVER=tcp:192.168.18.71
      - DOORBELL_FILE=/app/doorbell_sound.mp3
      - HUMAN_DOORBELL_FILE=/app/human_doorbell_sound.mp3
      - DOORBELL_REPEAT=3
      - HUMAN_DOORBELL_REPEAT=1
      - PLAYBACK_ROUNDS=2

networks:
  caddy_net:
    external: true

