services:
  personal_website:
    build: .
    container_name: personal_website
    restart: unless-stopped
    networks:
      - caddy_net
    environment:
      - PULSE_SERVER=tcp:192.168.18.71
      - BELL_PLAY_COMMAND=paplay /usr/share/sounds/alsa/Front_Center.wav
    volumes:
      - /usr/share/sounds/alsa/Front_Center.wav:/usr/share/sounds/alsa/Front_Center.wav:ro

networks:
  caddy_net:
    external: true

